import requests
import xml

# fetch("https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse_Advanced", {
#     "credentials":"include","headers":{
#         "accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
#         "accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3",
#         "cache-control":"max-age=0","content-type":"application/x-www-form-urlencoded",
#         "upgrade-insecure-requests":"1"
#         },
#     "referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse",
#     "referrerPolicy":"no-referrer-when-downgrade",
#     "body":"rsts=dummy&crn=dummy&term_in=201909&sel_subj=dummy&sel_day=dummy&sel_schd=dummy&sel_insm=dummy&sel_camp=dummy&sel_levl=dummy&sel_sess=dummy&sel_instr=dummy&sel_ptrm=dummy&sel_attr=dummy&sel_subj=BIOL&sel_coll=SC&sel_crse=&sel_title=&sel_schd=%25&sel_from_cred=&sel_to_cred=&sel_levl=%25&sel_ptrm=%25&sel_instr=%25&sel_attr=%25&begin_hh=0&begin_mi=0&begin_ap=a&end_hh=0&end_mi=0&end_ap=a&SUB_BTN=Get+Course+Sections&path=1",
#     "method":"POST",
#     "mode":"cors"
# })
# fetch("https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","cache-control":"max-age=0","content-type":"application/x-www-form-urlencoded","upgrade-insecure-requests":"1"},"referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":"rsts=dummy&crn=dummy&term_in=201909&sel_subj=dummy&sel_day=dummy&sel_schd=dummy&sel_insm=dummy&sel_camp=dummy&sel_levl=dummy&sel_sess=dummy&sel_instr=dummy&sel_ptrm=dummy&sel_attr=dummy&sel_crse=&sel_title=&sel_from_cred=&sel_to_cred=&sel_ptrm=%25&begin_hh=0&begin_mi=0&end_hh=0&end_mi=0&begin_ap=x&end_ap=y&path=1&SUB_BTN=Advanced+Search","method":"POST","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","cache-control":"max-age=0","content-type":"application/x-www-form-urlencoded","upgrade-insecure-requests":"1"},"referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.p_sel_crse_search","referrerPolicy":"no-referrer-when-downgrade","body":"p_calling_proc=P_CrseSearch&search_mode_in=NON_NT&p_term=201909","method":"POST","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/pban1/bwskfcls.p_sel_crse_search", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","upgrade-insecure-requests":"1"},"referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_RegMnu&param_name=SRCH_MODE&param_val=NON_NT","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_RegMnu&param_name=SRCH_MODE&param_val=NON_NT", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","upgrade-insecure-requests":"1"},"referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_StuMainMnu","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_StuMainMnu", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","upgrade-insecure-requests":"1"},"referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu&msg=WELCOME+%3Cb%3EWelcome,+Ryan+B.+Au,+to+Minerva+-+McGill%27s+Administrative+Systems!%3C%2Fb%3ESep+05,+201902%3A12+PM","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu&msg=WELCOME+%3Cb%3EWelcome,+Ryan+B.+Au,+to+Minerva+-+McGill%27s+Administrative+Systems!%3C%2Fb%3ESep+05,+201902%3A12+PM", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","upgrade-insecure-requests":"1"},"referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_ValLogin","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/pban1/twbkwbis.P_ValLogin", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","cache-control":"max-age=0","content-type":"application/x-www-form-urlencoded","upgrade-insecure-requests":"1"},"referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_WWWLogin","referrerPolicy":"no-referrer-when-downgrade","body":"sid=ryan.au%40mail.mcgill.ca&PIN=%40Green1000","method":"POST","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/pban1/twbkwbis.P_WWWLogin", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","cache-control":"max-age=0","upgrade-insecure-requests":"1"},"referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/mcggifs/Log_in.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_WWWLogin","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_WWWLogin","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/js/jquery/jquery-1.3.2.min.js", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_WWWLogin","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/favicon.ico", {"credentials":"include","headers":{"accept":"image/webp,image/apng,image/*,*/*;q=0.8","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3","cache-control":"no-cache","pragma":"no-cache"},"referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_WWWLogin","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=", {"credentials":"omit","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAYdJREFUOBGVVLuKwkAUPTErioVgY5WF2AhpFKz8AC0W0vgTK9injvkMt7HyB6zWSuy1s1WRXUJQ0cJCxSLOnSSzcYmaDGTmPs45M3fuEMmyrA/XdXvse0eMIUnSD4N9drvdb4KnkpCJ4G/0RTYNEoi1swf35jAnFU68snO5HMrl8h0skYCqqmg0GtEC2WxWJDKZDNhlCT+cE0HfeKNV13XUajUMBgPs93t0Oh3Yto1+v3+X+08mP1EJUQKSaZouJeiY5/OZY6iEy+UShRcxVuIvc9riBAGZEK/IhGGtVNjS43dAgWej2WyiUqlAlmWs12sMh0OcTicuIk7wTOBwOGA+n2O5XELTNJRKJQFP+W9bBKKM6XSK4/GIfD4Px3G4UIAjgXYckXq9DkVRsN1ukU6nAz7+XosIeUbQHfKIcL1eUa1W0Wq1MB6PMZlMODDWJRqGgd1uh0KhwEmbzYavND0UoD77rcJoNEKxWOS1LxYLrFYrLkCYhwIMQXdDPxplNptxQngiMmFuABiQmENn7wkAAAAASUVORK5CYII=", {"credentials":"omit","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAWRJREFUOBGlU7GOgkAQHbnrSAxGK3IVUPId5M7EDlpKvoCaXM8P8AWUfoCJhYWdjQkaa++MGLWmIZmb3YQ54Lg7vZtkd9/OvHn7NgsAAC809jTwxiG4zzQ47mmuDhE9Mno0i+RfQvSCck/naDSCyWTypaWy9evqeR5mWVbxpBA70DSNlfv9PigKl6Be6/Wkc+ZKVpIkcLlcwHEcMAwD8jyHxWIhSfUad9XA5zG15L1Q3olsVndDugKSVd6TYBd+o/z4P88ojL6LqUu9kYvjGI/HI16vV5xOpzgcDrn+QAKvQuWnsCwLSADO5zO4rgur1Qq22y237Amx4nc4DENcLpe4Xq9xMBjU+bf9TIfDAcuyxDRNUdf1hgBbaQEmqaoqse/7KCKKIq49tpo6t6fTCXa7HZimKeubzYZ5ze+S0xKId34SKAgCsG0biqKA2WwG8/lcEmiSz1ht2uuYEkKE7bawqI0/AJ5yzXcdXYlXAAAAAElFTkSuQmCC", {"credentials":"omit","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultapp.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu&msg=WELCOME+%3Cb%3EWelcome,+Ryan+B.+Au,+to+Minerva+-+McGill%27s+Administrative+Systems!%3C%2Fb%3ESep+05,+201902%3A12+PM","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_tab_corner_right.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu&msg=WELCOME+%3Cb%3EWelcome,+Ryan+B.+Au,+to+Minerva+-+McGill%27s+Administrative+Systems!%3C%2Fb%3ESep+05,+201902%3A12+PM","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu&msg=WELCOME+%3Cb%3EWelcome,+Ryan+B.+Au,+to+Minerva+-+McGill%27s+Administrative+Systems!%3C%2Fb%3ESep+05,+201902%3A12+PM","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultprint.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu&msg=WELCOME+%3Cb%3EWelcome,+Ryan+B.+Au,+to+Minerva+-+McGill%27s+Administrative+Systems!%3C%2Fb%3ESep+05,+201902%3A12+PM","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultapp.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_StuMainMnu","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_tab_corner_right.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_StuMainMnu","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_StuMainMnu","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultprint.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_StuMainMnu","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultapp.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_RegMnu&param_name=SRCH_MODE&param_val=NON_NT","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_tab_corner_right.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_RegMnu&param_name=SRCH_MODE&param_val=NON_NT","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_RegMnu&param_name=SRCH_MODE&param_val=NON_NT","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_info_cascade.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_RegMnu&param_name=SRCH_MODE&param_val=NON_NT","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultprint.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/twbkwbis.P_GenMenu?name=bmenu.P_RegMnu&param_name=SRCH_MODE&param_val=NON_NT","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultapp.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.p_sel_crse_search","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_tab_corner_right.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.p_sel_crse_search","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.p_sel_crse_search","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultprint.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.p_sel_crse_search","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultapp.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_tab_corner_right.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_info_cascade.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_required_cascade.png", {"credentials":"include","headers":{"accept":"image/webp,image/apng,image/*,*/*;q=0.8","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3"},"referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultprint.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultapp.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_tab_corner_right.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/twgginfo.gif", {"credentials":"include","headers":{"accept":"image/webp,image/apng,image/*,*/*;q=0.8","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3"},"referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_required.gif", {"credentials":"include","headers":{"accept":"image/webp,image/apng,image/*,*/*;q=0.8","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3"},"referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_required_cascade.png", {"credentials":"include","headers":{"accept":"image/webp,image/apng,image/*,*/*;q=0.8","accept-language":"en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7,ru-RU;q=0.6,ru;q=0.5,es;q=0.4,ml;q=0.3"},"referrer":"https://horizon.mcgill.ca/pban1/bwckgens.p_proc_term_date","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultprint.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=", {"credentials":"omit","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==", {"credentials":"omit","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAvElEQVQ4T2NkoBAwIukXALL9gViBgJkPgPIbgfgDSB2yAQVAfj+RDioEqpuAbkADUKAeiB0JGLIfKN8IxCD1KC6AGYDsqgtANf+B2BDJUBCfaAM2QDUGkGMAcpjA/Qx1EVEugHkJZDlcA7EGgKJSHi0wHwL5D4g1wAGoEISRwQEgB4SJCkSQZns0Aw6SYgDICyCMDEDOJ8oL6E5HMwfsDayxQHFSBmUmUIJBdzq6C0DeWAATRE626AqJ4gMAKh82EQu8MAEAAAAASUVORK5CYII=", {"credentials":"omit","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultapp.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse_Advanced","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_tab_corner_right.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse_Advanced","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_transparent.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse_Advanced","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/wtlgifs/web_info_cascade.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse_Advanced","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/web_defaultprint.css", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/pban1/bwskfcls.P_GetCrse_Advanced","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg-strip.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/com-header-bg.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/bg_button.gif", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"}); ;
# fetch("https://horizon.mcgill.ca/css/images/content-bg-tc-dark.png", {"credentials":"omit","referrer":"https://horizon.mcgill.ca/css/web_defaultapp.css","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"});

request_headers = {
    'Origin':'https://horizon.mcgill.ca',
    'Upgrade-Insecure-Requests':'1',
    'DNT':'1',
    'Content-Type':'application/x-www-form-urlencoded',
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36',
    'Sec-Fetch-Mode':'navigate',
    'Sec-Fetch-User':'?1',
    'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',

}
data = {
    'attr_in':'',
    'coll_in':'%',
    'cred_from_in':'',
    'cred_to_in':'',
    'crse_end_in':'220',
    'crse_strt_in':'214',
    'dept_in':'%',
    'divs_in':'%',
    'last_updated':'',
    'levl_in':'',
    'schd_in':'',
    'subj_in':'\tANAT\t',
    'term_in':'201909',
    'title_in':'%%',
}

r = requests.post('https://horizon.mcgill.ca/pban1/bwckctlg.xml',data=data,headers=request_headers)